// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

package com.xalpol12.wsserver.protos;

public interface ChatMessagePayloadOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.xalpol12.websocket.ChatMessagePayload)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string sender = 1;</code>
   * @return The sender.
   */
  java.lang.String getSender();
  /**
   * <code>string sender = 1;</code>
   * @return The bytes for sender.
   */
  com.google.protobuf.ByteString
      getSenderBytes();

  /**
   * <code>string content = 2;</code>
   * @return The content.
   */
  java.lang.String getContent();
  /**
   * <code>string content = 2;</code>
   * @return The bytes for content.
   */
  com.google.protobuf.ByteString
      getContentBytes();
}
