// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

package com.xalpol12.wsserver.protos;

/**
 * Protobuf type {@code com.xalpol12.websocket.CustomMessage}
 */
public final class CustomMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.xalpol12.websocket.CustomMessage)
    CustomMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CustomMessage.newBuilder() to construct.
  private CustomMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CustomMessage() {
    messageType_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CustomMessage();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.xalpol12.wsserver.protos.CustomMessageProtos.internal_static_com_xalpol12_websocket_CustomMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.xalpol12.wsserver.protos.CustomMessageProtos.internal_static_com_xalpol12_websocket_CustomMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.xalpol12.wsserver.protos.CustomMessage.class, com.xalpol12.wsserver.protos.CustomMessage.Builder.class);
  }

  private int payloadCase_ = 0;
  private java.lang.Object payload_;
  public enum PayloadCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    HANDSHAKEPAYLOAD(2),
    DRAWINGPAYLOAD(3),
    CHATMESSAGEPAYLOAD(4),
    GAMETIMERPAYLOAD(5),
    NEWWORDPAYLOAD(6),
    GAMESCOREPAYLOAD(7),
    CLEARBOARDPAYLOAD(8),
    PAYLOAD_NOT_SET(0);
    private final int value;
    private PayloadCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static PayloadCase valueOf(int value) {
      return forNumber(value);
    }

    public static PayloadCase forNumber(int value) {
      switch (value) {
        case 2: return HANDSHAKEPAYLOAD;
        case 3: return DRAWINGPAYLOAD;
        case 4: return CHATMESSAGEPAYLOAD;
        case 5: return GAMETIMERPAYLOAD;
        case 6: return NEWWORDPAYLOAD;
        case 7: return GAMESCOREPAYLOAD;
        case 8: return CLEARBOARDPAYLOAD;
        case 0: return PAYLOAD_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public PayloadCase
  getPayloadCase() {
    return PayloadCase.forNumber(
        payloadCase_);
  }

  public static final int MESSAGETYPE_FIELD_NUMBER = 1;
  private int messageType_ = 0;
  /**
   * <code>.com.xalpol12.websocket.MessageType messageType = 1;</code>
   * @return The enum numeric value on the wire for messageType.
   */
  @java.lang.Override public int getMessageTypeValue() {
    return messageType_;
  }
  /**
   * <code>.com.xalpol12.websocket.MessageType messageType = 1;</code>
   * @return The messageType.
   */
  @java.lang.Override public com.xalpol12.wsserver.protos.MessageType getMessageType() {
    com.xalpol12.wsserver.protos.MessageType result = com.xalpol12.wsserver.protos.MessageType.forNumber(messageType_);
    return result == null ? com.xalpol12.wsserver.protos.MessageType.UNRECOGNIZED : result;
  }

  public static final int HANDSHAKEPAYLOAD_FIELD_NUMBER = 2;
  /**
   * <code>.com.xalpol12.websocket.HandshakePayload HandshakePayload = 2;</code>
   * @return Whether the handshakePayload field is set.
   */
  @java.lang.Override
  public boolean hasHandshakePayload() {
    return payloadCase_ == 2;
  }
  /**
   * <code>.com.xalpol12.websocket.HandshakePayload HandshakePayload = 2;</code>
   * @return The handshakePayload.
   */
  @java.lang.Override
  public com.xalpol12.wsserver.protos.HandshakePayload getHandshakePayload() {
    if (payloadCase_ == 2) {
       return (com.xalpol12.wsserver.protos.HandshakePayload) payload_;
    }
    return com.xalpol12.wsserver.protos.HandshakePayload.getDefaultInstance();
  }
  /**
   * <code>.com.xalpol12.websocket.HandshakePayload HandshakePayload = 2;</code>
   */
  @java.lang.Override
  public com.xalpol12.wsserver.protos.HandshakePayloadOrBuilder getHandshakePayloadOrBuilder() {
    if (payloadCase_ == 2) {
       return (com.xalpol12.wsserver.protos.HandshakePayload) payload_;
    }
    return com.xalpol12.wsserver.protos.HandshakePayload.getDefaultInstance();
  }

  public static final int DRAWINGPAYLOAD_FIELD_NUMBER = 3;
  /**
   * <code>.com.xalpol12.websocket.DrawingPayload drawingPayload = 3;</code>
   * @return Whether the drawingPayload field is set.
   */
  @java.lang.Override
  public boolean hasDrawingPayload() {
    return payloadCase_ == 3;
  }
  /**
   * <code>.com.xalpol12.websocket.DrawingPayload drawingPayload = 3;</code>
   * @return The drawingPayload.
   */
  @java.lang.Override
  public com.xalpol12.wsserver.protos.DrawingPayload getDrawingPayload() {
    if (payloadCase_ == 3) {
       return (com.xalpol12.wsserver.protos.DrawingPayload) payload_;
    }
    return com.xalpol12.wsserver.protos.DrawingPayload.getDefaultInstance();
  }
  /**
   * <code>.com.xalpol12.websocket.DrawingPayload drawingPayload = 3;</code>
   */
  @java.lang.Override
  public com.xalpol12.wsserver.protos.DrawingPayloadOrBuilder getDrawingPayloadOrBuilder() {
    if (payloadCase_ == 3) {
       return (com.xalpol12.wsserver.protos.DrawingPayload) payload_;
    }
    return com.xalpol12.wsserver.protos.DrawingPayload.getDefaultInstance();
  }

  public static final int CHATMESSAGEPAYLOAD_FIELD_NUMBER = 4;
  /**
   * <code>.com.xalpol12.websocket.ChatMessagePayload chatMessagePayload = 4;</code>
   * @return Whether the chatMessagePayload field is set.
   */
  @java.lang.Override
  public boolean hasChatMessagePayload() {
    return payloadCase_ == 4;
  }
  /**
   * <code>.com.xalpol12.websocket.ChatMessagePayload chatMessagePayload = 4;</code>
   * @return The chatMessagePayload.
   */
  @java.lang.Override
  public com.xalpol12.wsserver.protos.ChatMessagePayload getChatMessagePayload() {
    if (payloadCase_ == 4) {
       return (com.xalpol12.wsserver.protos.ChatMessagePayload) payload_;
    }
    return com.xalpol12.wsserver.protos.ChatMessagePayload.getDefaultInstance();
  }
  /**
   * <code>.com.xalpol12.websocket.ChatMessagePayload chatMessagePayload = 4;</code>
   */
  @java.lang.Override
  public com.xalpol12.wsserver.protos.ChatMessagePayloadOrBuilder getChatMessagePayloadOrBuilder() {
    if (payloadCase_ == 4) {
       return (com.xalpol12.wsserver.protos.ChatMessagePayload) payload_;
    }
    return com.xalpol12.wsserver.protos.ChatMessagePayload.getDefaultInstance();
  }

  public static final int GAMETIMERPAYLOAD_FIELD_NUMBER = 5;
  /**
   * <code>.com.xalpol12.websocket.GameTimerPayload gameTimerPayload = 5;</code>
   * @return Whether the gameTimerPayload field is set.
   */
  @java.lang.Override
  public boolean hasGameTimerPayload() {
    return payloadCase_ == 5;
  }
  /**
   * <code>.com.xalpol12.websocket.GameTimerPayload gameTimerPayload = 5;</code>
   * @return The gameTimerPayload.
   */
  @java.lang.Override
  public com.xalpol12.wsserver.protos.GameTimerPayload getGameTimerPayload() {
    if (payloadCase_ == 5) {
       return (com.xalpol12.wsserver.protos.GameTimerPayload) payload_;
    }
    return com.xalpol12.wsserver.protos.GameTimerPayload.getDefaultInstance();
  }
  /**
   * <code>.com.xalpol12.websocket.GameTimerPayload gameTimerPayload = 5;</code>
   */
  @java.lang.Override
  public com.xalpol12.wsserver.protos.GameTimerPayloadOrBuilder getGameTimerPayloadOrBuilder() {
    if (payloadCase_ == 5) {
       return (com.xalpol12.wsserver.protos.GameTimerPayload) payload_;
    }
    return com.xalpol12.wsserver.protos.GameTimerPayload.getDefaultInstance();
  }

  public static final int NEWWORDPAYLOAD_FIELD_NUMBER = 6;
  /**
   * <code>.com.xalpol12.websocket.NewWordPayload newWordPayload = 6;</code>
   * @return Whether the newWordPayload field is set.
   */
  @java.lang.Override
  public boolean hasNewWordPayload() {
    return payloadCase_ == 6;
  }
  /**
   * <code>.com.xalpol12.websocket.NewWordPayload newWordPayload = 6;</code>
   * @return The newWordPayload.
   */
  @java.lang.Override
  public com.xalpol12.wsserver.protos.NewWordPayload getNewWordPayload() {
    if (payloadCase_ == 6) {
       return (com.xalpol12.wsserver.protos.NewWordPayload) payload_;
    }
    return com.xalpol12.wsserver.protos.NewWordPayload.getDefaultInstance();
  }
  /**
   * <code>.com.xalpol12.websocket.NewWordPayload newWordPayload = 6;</code>
   */
  @java.lang.Override
  public com.xalpol12.wsserver.protos.NewWordPayloadOrBuilder getNewWordPayloadOrBuilder() {
    if (payloadCase_ == 6) {
       return (com.xalpol12.wsserver.protos.NewWordPayload) payload_;
    }
    return com.xalpol12.wsserver.protos.NewWordPayload.getDefaultInstance();
  }

  public static final int GAMESCOREPAYLOAD_FIELD_NUMBER = 7;
  /**
   * <code>.com.xalpol12.websocket.GameScorePayload gameScorePayload = 7;</code>
   * @return Whether the gameScorePayload field is set.
   */
  @java.lang.Override
  public boolean hasGameScorePayload() {
    return payloadCase_ == 7;
  }
  /**
   * <code>.com.xalpol12.websocket.GameScorePayload gameScorePayload = 7;</code>
   * @return The gameScorePayload.
   */
  @java.lang.Override
  public com.xalpol12.wsserver.protos.GameScorePayload getGameScorePayload() {
    if (payloadCase_ == 7) {
       return (com.xalpol12.wsserver.protos.GameScorePayload) payload_;
    }
    return com.xalpol12.wsserver.protos.GameScorePayload.getDefaultInstance();
  }
  /**
   * <code>.com.xalpol12.websocket.GameScorePayload gameScorePayload = 7;</code>
   */
  @java.lang.Override
  public com.xalpol12.wsserver.protos.GameScorePayloadOrBuilder getGameScorePayloadOrBuilder() {
    if (payloadCase_ == 7) {
       return (com.xalpol12.wsserver.protos.GameScorePayload) payload_;
    }
    return com.xalpol12.wsserver.protos.GameScorePayload.getDefaultInstance();
  }

  public static final int CLEARBOARDPAYLOAD_FIELD_NUMBER = 8;
  /**
   * <code>.com.xalpol12.websocket.ClearBoardPayload clearBoardPayload = 8;</code>
   * @return Whether the clearBoardPayload field is set.
   */
  @java.lang.Override
  public boolean hasClearBoardPayload() {
    return payloadCase_ == 8;
  }
  /**
   * <code>.com.xalpol12.websocket.ClearBoardPayload clearBoardPayload = 8;</code>
   * @return The clearBoardPayload.
   */
  @java.lang.Override
  public com.xalpol12.wsserver.protos.ClearBoardPayload getClearBoardPayload() {
    if (payloadCase_ == 8) {
       return (com.xalpol12.wsserver.protos.ClearBoardPayload) payload_;
    }
    return com.xalpol12.wsserver.protos.ClearBoardPayload.getDefaultInstance();
  }
  /**
   * <code>.com.xalpol12.websocket.ClearBoardPayload clearBoardPayload = 8;</code>
   */
  @java.lang.Override
  public com.xalpol12.wsserver.protos.ClearBoardPayloadOrBuilder getClearBoardPayloadOrBuilder() {
    if (payloadCase_ == 8) {
       return (com.xalpol12.wsserver.protos.ClearBoardPayload) payload_;
    }
    return com.xalpol12.wsserver.protos.ClearBoardPayload.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (messageType_ != com.xalpol12.wsserver.protos.MessageType.HANDSHAKE.getNumber()) {
      output.writeEnum(1, messageType_);
    }
    if (payloadCase_ == 2) {
      output.writeMessage(2, (com.xalpol12.wsserver.protos.HandshakePayload) payload_);
    }
    if (payloadCase_ == 3) {
      output.writeMessage(3, (com.xalpol12.wsserver.protos.DrawingPayload) payload_);
    }
    if (payloadCase_ == 4) {
      output.writeMessage(4, (com.xalpol12.wsserver.protos.ChatMessagePayload) payload_);
    }
    if (payloadCase_ == 5) {
      output.writeMessage(5, (com.xalpol12.wsserver.protos.GameTimerPayload) payload_);
    }
    if (payloadCase_ == 6) {
      output.writeMessage(6, (com.xalpol12.wsserver.protos.NewWordPayload) payload_);
    }
    if (payloadCase_ == 7) {
      output.writeMessage(7, (com.xalpol12.wsserver.protos.GameScorePayload) payload_);
    }
    if (payloadCase_ == 8) {
      output.writeMessage(8, (com.xalpol12.wsserver.protos.ClearBoardPayload) payload_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (messageType_ != com.xalpol12.wsserver.protos.MessageType.HANDSHAKE.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, messageType_);
    }
    if (payloadCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (com.xalpol12.wsserver.protos.HandshakePayload) payload_);
    }
    if (payloadCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (com.xalpol12.wsserver.protos.DrawingPayload) payload_);
    }
    if (payloadCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, (com.xalpol12.wsserver.protos.ChatMessagePayload) payload_);
    }
    if (payloadCase_ == 5) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, (com.xalpol12.wsserver.protos.GameTimerPayload) payload_);
    }
    if (payloadCase_ == 6) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, (com.xalpol12.wsserver.protos.NewWordPayload) payload_);
    }
    if (payloadCase_ == 7) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, (com.xalpol12.wsserver.protos.GameScorePayload) payload_);
    }
    if (payloadCase_ == 8) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, (com.xalpol12.wsserver.protos.ClearBoardPayload) payload_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.xalpol12.wsserver.protos.CustomMessage)) {
      return super.equals(obj);
    }
    com.xalpol12.wsserver.protos.CustomMessage other = (com.xalpol12.wsserver.protos.CustomMessage) obj;

    if (messageType_ != other.messageType_) return false;
    if (!getPayloadCase().equals(other.getPayloadCase())) return false;
    switch (payloadCase_) {
      case 2:
        if (!getHandshakePayload()
            .equals(other.getHandshakePayload())) return false;
        break;
      case 3:
        if (!getDrawingPayload()
            .equals(other.getDrawingPayload())) return false;
        break;
      case 4:
        if (!getChatMessagePayload()
            .equals(other.getChatMessagePayload())) return false;
        break;
      case 5:
        if (!getGameTimerPayload()
            .equals(other.getGameTimerPayload())) return false;
        break;
      case 6:
        if (!getNewWordPayload()
            .equals(other.getNewWordPayload())) return false;
        break;
      case 7:
        if (!getGameScorePayload()
            .equals(other.getGameScorePayload())) return false;
        break;
      case 8:
        if (!getClearBoardPayload()
            .equals(other.getClearBoardPayload())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MESSAGETYPE_FIELD_NUMBER;
    hash = (53 * hash) + messageType_;
    switch (payloadCase_) {
      case 2:
        hash = (37 * hash) + HANDSHAKEPAYLOAD_FIELD_NUMBER;
        hash = (53 * hash) + getHandshakePayload().hashCode();
        break;
      case 3:
        hash = (37 * hash) + DRAWINGPAYLOAD_FIELD_NUMBER;
        hash = (53 * hash) + getDrawingPayload().hashCode();
        break;
      case 4:
        hash = (37 * hash) + CHATMESSAGEPAYLOAD_FIELD_NUMBER;
        hash = (53 * hash) + getChatMessagePayload().hashCode();
        break;
      case 5:
        hash = (37 * hash) + GAMETIMERPAYLOAD_FIELD_NUMBER;
        hash = (53 * hash) + getGameTimerPayload().hashCode();
        break;
      case 6:
        hash = (37 * hash) + NEWWORDPAYLOAD_FIELD_NUMBER;
        hash = (53 * hash) + getNewWordPayload().hashCode();
        break;
      case 7:
        hash = (37 * hash) + GAMESCOREPAYLOAD_FIELD_NUMBER;
        hash = (53 * hash) + getGameScorePayload().hashCode();
        break;
      case 8:
        hash = (37 * hash) + CLEARBOARDPAYLOAD_FIELD_NUMBER;
        hash = (53 * hash) + getClearBoardPayload().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.xalpol12.wsserver.protos.CustomMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xalpol12.wsserver.protos.CustomMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xalpol12.wsserver.protos.CustomMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xalpol12.wsserver.protos.CustomMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xalpol12.wsserver.protos.CustomMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xalpol12.wsserver.protos.CustomMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xalpol12.wsserver.protos.CustomMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xalpol12.wsserver.protos.CustomMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.xalpol12.wsserver.protos.CustomMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.xalpol12.wsserver.protos.CustomMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.xalpol12.wsserver.protos.CustomMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xalpol12.wsserver.protos.CustomMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.xalpol12.wsserver.protos.CustomMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.xalpol12.websocket.CustomMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.xalpol12.websocket.CustomMessage)
      com.xalpol12.wsserver.protos.CustomMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xalpol12.wsserver.protos.CustomMessageProtos.internal_static_com_xalpol12_websocket_CustomMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xalpol12.wsserver.protos.CustomMessageProtos.internal_static_com_xalpol12_websocket_CustomMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xalpol12.wsserver.protos.CustomMessage.class, com.xalpol12.wsserver.protos.CustomMessage.Builder.class);
    }

    // Construct using com.xalpol12.wsserver.protos.CustomMessage.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      messageType_ = 0;
      if (handshakePayloadBuilder_ != null) {
        handshakePayloadBuilder_.clear();
      }
      if (drawingPayloadBuilder_ != null) {
        drawingPayloadBuilder_.clear();
      }
      if (chatMessagePayloadBuilder_ != null) {
        chatMessagePayloadBuilder_.clear();
      }
      if (gameTimerPayloadBuilder_ != null) {
        gameTimerPayloadBuilder_.clear();
      }
      if (newWordPayloadBuilder_ != null) {
        newWordPayloadBuilder_.clear();
      }
      if (gameScorePayloadBuilder_ != null) {
        gameScorePayloadBuilder_.clear();
      }
      if (clearBoardPayloadBuilder_ != null) {
        clearBoardPayloadBuilder_.clear();
      }
      payloadCase_ = 0;
      payload_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.xalpol12.wsserver.protos.CustomMessageProtos.internal_static_com_xalpol12_websocket_CustomMessage_descriptor;
    }

    @java.lang.Override
    public com.xalpol12.wsserver.protos.CustomMessage getDefaultInstanceForType() {
      return com.xalpol12.wsserver.protos.CustomMessage.getDefaultInstance();
    }

    @java.lang.Override
    public com.xalpol12.wsserver.protos.CustomMessage build() {
      com.xalpol12.wsserver.protos.CustomMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.xalpol12.wsserver.protos.CustomMessage buildPartial() {
      com.xalpol12.wsserver.protos.CustomMessage result = new com.xalpol12.wsserver.protos.CustomMessage(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(com.xalpol12.wsserver.protos.CustomMessage result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.messageType_ = messageType_;
      }
    }

    private void buildPartialOneofs(com.xalpol12.wsserver.protos.CustomMessage result) {
      result.payloadCase_ = payloadCase_;
      result.payload_ = this.payload_;
      if (payloadCase_ == 2 &&
          handshakePayloadBuilder_ != null) {
        result.payload_ = handshakePayloadBuilder_.build();
      }
      if (payloadCase_ == 3 &&
          drawingPayloadBuilder_ != null) {
        result.payload_ = drawingPayloadBuilder_.build();
      }
      if (payloadCase_ == 4 &&
          chatMessagePayloadBuilder_ != null) {
        result.payload_ = chatMessagePayloadBuilder_.build();
      }
      if (payloadCase_ == 5 &&
          gameTimerPayloadBuilder_ != null) {
        result.payload_ = gameTimerPayloadBuilder_.build();
      }
      if (payloadCase_ == 6 &&
          newWordPayloadBuilder_ != null) {
        result.payload_ = newWordPayloadBuilder_.build();
      }
      if (payloadCase_ == 7 &&
          gameScorePayloadBuilder_ != null) {
        result.payload_ = gameScorePayloadBuilder_.build();
      }
      if (payloadCase_ == 8 &&
          clearBoardPayloadBuilder_ != null) {
        result.payload_ = clearBoardPayloadBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.xalpol12.wsserver.protos.CustomMessage) {
        return mergeFrom((com.xalpol12.wsserver.protos.CustomMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.xalpol12.wsserver.protos.CustomMessage other) {
      if (other == com.xalpol12.wsserver.protos.CustomMessage.getDefaultInstance()) return this;
      if (other.messageType_ != 0) {
        setMessageTypeValue(other.getMessageTypeValue());
      }
      switch (other.getPayloadCase()) {
        case HANDSHAKEPAYLOAD: {
          mergeHandshakePayload(other.getHandshakePayload());
          break;
        }
        case DRAWINGPAYLOAD: {
          mergeDrawingPayload(other.getDrawingPayload());
          break;
        }
        case CHATMESSAGEPAYLOAD: {
          mergeChatMessagePayload(other.getChatMessagePayload());
          break;
        }
        case GAMETIMERPAYLOAD: {
          mergeGameTimerPayload(other.getGameTimerPayload());
          break;
        }
        case NEWWORDPAYLOAD: {
          mergeNewWordPayload(other.getNewWordPayload());
          break;
        }
        case GAMESCOREPAYLOAD: {
          mergeGameScorePayload(other.getGameScorePayload());
          break;
        }
        case CLEARBOARDPAYLOAD: {
          mergeClearBoardPayload(other.getClearBoardPayload());
          break;
        }
        case PAYLOAD_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              messageType_ = input.readEnum();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              input.readMessage(
                  getHandshakePayloadFieldBuilder().getBuilder(),
                  extensionRegistry);
              payloadCase_ = 2;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getDrawingPayloadFieldBuilder().getBuilder(),
                  extensionRegistry);
              payloadCase_ = 3;
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  getChatMessagePayloadFieldBuilder().getBuilder(),
                  extensionRegistry);
              payloadCase_ = 4;
              break;
            } // case 34
            case 42: {
              input.readMessage(
                  getGameTimerPayloadFieldBuilder().getBuilder(),
                  extensionRegistry);
              payloadCase_ = 5;
              break;
            } // case 42
            case 50: {
              input.readMessage(
                  getNewWordPayloadFieldBuilder().getBuilder(),
                  extensionRegistry);
              payloadCase_ = 6;
              break;
            } // case 50
            case 58: {
              input.readMessage(
                  getGameScorePayloadFieldBuilder().getBuilder(),
                  extensionRegistry);
              payloadCase_ = 7;
              break;
            } // case 58
            case 66: {
              input.readMessage(
                  getClearBoardPayloadFieldBuilder().getBuilder(),
                  extensionRegistry);
              payloadCase_ = 8;
              break;
            } // case 66
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int payloadCase_ = 0;
    private java.lang.Object payload_;
    public PayloadCase
        getPayloadCase() {
      return PayloadCase.forNumber(
          payloadCase_);
    }

    public Builder clearPayload() {
      payloadCase_ = 0;
      payload_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private int messageType_ = 0;
    /**
     * <code>.com.xalpol12.websocket.MessageType messageType = 1;</code>
     * @return The enum numeric value on the wire for messageType.
     */
    @java.lang.Override public int getMessageTypeValue() {
      return messageType_;
    }
    /**
     * <code>.com.xalpol12.websocket.MessageType messageType = 1;</code>
     * @param value The enum numeric value on the wire for messageType to set.
     * @return This builder for chaining.
     */
    public Builder setMessageTypeValue(int value) {
      messageType_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.com.xalpol12.websocket.MessageType messageType = 1;</code>
     * @return The messageType.
     */
    @java.lang.Override
    public com.xalpol12.wsserver.protos.MessageType getMessageType() {
      com.xalpol12.wsserver.protos.MessageType result = com.xalpol12.wsserver.protos.MessageType.forNumber(messageType_);
      return result == null ? com.xalpol12.wsserver.protos.MessageType.UNRECOGNIZED : result;
    }
    /**
     * <code>.com.xalpol12.websocket.MessageType messageType = 1;</code>
     * @param value The messageType to set.
     * @return This builder for chaining.
     */
    public Builder setMessageType(com.xalpol12.wsserver.protos.MessageType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      messageType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.com.xalpol12.websocket.MessageType messageType = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMessageType() {
      bitField0_ = (bitField0_ & ~0x00000001);
      messageType_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.xalpol12.wsserver.protos.HandshakePayload, com.xalpol12.wsserver.protos.HandshakePayload.Builder, com.xalpol12.wsserver.protos.HandshakePayloadOrBuilder> handshakePayloadBuilder_;
    /**
     * <code>.com.xalpol12.websocket.HandshakePayload HandshakePayload = 2;</code>
     * @return Whether the handshakePayload field is set.
     */
    @java.lang.Override
    public boolean hasHandshakePayload() {
      return payloadCase_ == 2;
    }
    /**
     * <code>.com.xalpol12.websocket.HandshakePayload HandshakePayload = 2;</code>
     * @return The handshakePayload.
     */
    @java.lang.Override
    public com.xalpol12.wsserver.protos.HandshakePayload getHandshakePayload() {
      if (handshakePayloadBuilder_ == null) {
        if (payloadCase_ == 2) {
          return (com.xalpol12.wsserver.protos.HandshakePayload) payload_;
        }
        return com.xalpol12.wsserver.protos.HandshakePayload.getDefaultInstance();
      } else {
        if (payloadCase_ == 2) {
          return handshakePayloadBuilder_.getMessage();
        }
        return com.xalpol12.wsserver.protos.HandshakePayload.getDefaultInstance();
      }
    }
    /**
     * <code>.com.xalpol12.websocket.HandshakePayload HandshakePayload = 2;</code>
     */
    public Builder setHandshakePayload(com.xalpol12.wsserver.protos.HandshakePayload value) {
      if (handshakePayloadBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        payload_ = value;
        onChanged();
      } else {
        handshakePayloadBuilder_.setMessage(value);
      }
      payloadCase_ = 2;
      return this;
    }
    /**
     * <code>.com.xalpol12.websocket.HandshakePayload HandshakePayload = 2;</code>
     */
    public Builder setHandshakePayload(
        com.xalpol12.wsserver.protos.HandshakePayload.Builder builderForValue) {
      if (handshakePayloadBuilder_ == null) {
        payload_ = builderForValue.build();
        onChanged();
      } else {
        handshakePayloadBuilder_.setMessage(builderForValue.build());
      }
      payloadCase_ = 2;
      return this;
    }
    /**
     * <code>.com.xalpol12.websocket.HandshakePayload HandshakePayload = 2;</code>
     */
    public Builder mergeHandshakePayload(com.xalpol12.wsserver.protos.HandshakePayload value) {
      if (handshakePayloadBuilder_ == null) {
        if (payloadCase_ == 2 &&
            payload_ != com.xalpol12.wsserver.protos.HandshakePayload.getDefaultInstance()) {
          payload_ = com.xalpol12.wsserver.protos.HandshakePayload.newBuilder((com.xalpol12.wsserver.protos.HandshakePayload) payload_)
              .mergeFrom(value).buildPartial();
        } else {
          payload_ = value;
        }
        onChanged();
      } else {
        if (payloadCase_ == 2) {
          handshakePayloadBuilder_.mergeFrom(value);
        } else {
          handshakePayloadBuilder_.setMessage(value);
        }
      }
      payloadCase_ = 2;
      return this;
    }
    /**
     * <code>.com.xalpol12.websocket.HandshakePayload HandshakePayload = 2;</code>
     */
    public Builder clearHandshakePayload() {
      if (handshakePayloadBuilder_ == null) {
        if (payloadCase_ == 2) {
          payloadCase_ = 0;
          payload_ = null;
          onChanged();
        }
      } else {
        if (payloadCase_ == 2) {
          payloadCase_ = 0;
          payload_ = null;
        }
        handshakePayloadBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.com.xalpol12.websocket.HandshakePayload HandshakePayload = 2;</code>
     */
    public com.xalpol12.wsserver.protos.HandshakePayload.Builder getHandshakePayloadBuilder() {
      return getHandshakePayloadFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.xalpol12.websocket.HandshakePayload HandshakePayload = 2;</code>
     */
    @java.lang.Override
    public com.xalpol12.wsserver.protos.HandshakePayloadOrBuilder getHandshakePayloadOrBuilder() {
      if ((payloadCase_ == 2) && (handshakePayloadBuilder_ != null)) {
        return handshakePayloadBuilder_.getMessageOrBuilder();
      } else {
        if (payloadCase_ == 2) {
          return (com.xalpol12.wsserver.protos.HandshakePayload) payload_;
        }
        return com.xalpol12.wsserver.protos.HandshakePayload.getDefaultInstance();
      }
    }
    /**
     * <code>.com.xalpol12.websocket.HandshakePayload HandshakePayload = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.xalpol12.wsserver.protos.HandshakePayload, com.xalpol12.wsserver.protos.HandshakePayload.Builder, com.xalpol12.wsserver.protos.HandshakePayloadOrBuilder> 
        getHandshakePayloadFieldBuilder() {
      if (handshakePayloadBuilder_ == null) {
        if (!(payloadCase_ == 2)) {
          payload_ = com.xalpol12.wsserver.protos.HandshakePayload.getDefaultInstance();
        }
        handshakePayloadBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.xalpol12.wsserver.protos.HandshakePayload, com.xalpol12.wsserver.protos.HandshakePayload.Builder, com.xalpol12.wsserver.protos.HandshakePayloadOrBuilder>(
                (com.xalpol12.wsserver.protos.HandshakePayload) payload_,
                getParentForChildren(),
                isClean());
        payload_ = null;
      }
      payloadCase_ = 2;
      onChanged();
      return handshakePayloadBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.xalpol12.wsserver.protos.DrawingPayload, com.xalpol12.wsserver.protos.DrawingPayload.Builder, com.xalpol12.wsserver.protos.DrawingPayloadOrBuilder> drawingPayloadBuilder_;
    /**
     * <code>.com.xalpol12.websocket.DrawingPayload drawingPayload = 3;</code>
     * @return Whether the drawingPayload field is set.
     */
    @java.lang.Override
    public boolean hasDrawingPayload() {
      return payloadCase_ == 3;
    }
    /**
     * <code>.com.xalpol12.websocket.DrawingPayload drawingPayload = 3;</code>
     * @return The drawingPayload.
     */
    @java.lang.Override
    public com.xalpol12.wsserver.protos.DrawingPayload getDrawingPayload() {
      if (drawingPayloadBuilder_ == null) {
        if (payloadCase_ == 3) {
          return (com.xalpol12.wsserver.protos.DrawingPayload) payload_;
        }
        return com.xalpol12.wsserver.protos.DrawingPayload.getDefaultInstance();
      } else {
        if (payloadCase_ == 3) {
          return drawingPayloadBuilder_.getMessage();
        }
        return com.xalpol12.wsserver.protos.DrawingPayload.getDefaultInstance();
      }
    }
    /**
     * <code>.com.xalpol12.websocket.DrawingPayload drawingPayload = 3;</code>
     */
    public Builder setDrawingPayload(com.xalpol12.wsserver.protos.DrawingPayload value) {
      if (drawingPayloadBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        payload_ = value;
        onChanged();
      } else {
        drawingPayloadBuilder_.setMessage(value);
      }
      payloadCase_ = 3;
      return this;
    }
    /**
     * <code>.com.xalpol12.websocket.DrawingPayload drawingPayload = 3;</code>
     */
    public Builder setDrawingPayload(
        com.xalpol12.wsserver.protos.DrawingPayload.Builder builderForValue) {
      if (drawingPayloadBuilder_ == null) {
        payload_ = builderForValue.build();
        onChanged();
      } else {
        drawingPayloadBuilder_.setMessage(builderForValue.build());
      }
      payloadCase_ = 3;
      return this;
    }
    /**
     * <code>.com.xalpol12.websocket.DrawingPayload drawingPayload = 3;</code>
     */
    public Builder mergeDrawingPayload(com.xalpol12.wsserver.protos.DrawingPayload value) {
      if (drawingPayloadBuilder_ == null) {
        if (payloadCase_ == 3 &&
            payload_ != com.xalpol12.wsserver.protos.DrawingPayload.getDefaultInstance()) {
          payload_ = com.xalpol12.wsserver.protos.DrawingPayload.newBuilder((com.xalpol12.wsserver.protos.DrawingPayload) payload_)
              .mergeFrom(value).buildPartial();
        } else {
          payload_ = value;
        }
        onChanged();
      } else {
        if (payloadCase_ == 3) {
          drawingPayloadBuilder_.mergeFrom(value);
        } else {
          drawingPayloadBuilder_.setMessage(value);
        }
      }
      payloadCase_ = 3;
      return this;
    }
    /**
     * <code>.com.xalpol12.websocket.DrawingPayload drawingPayload = 3;</code>
     */
    public Builder clearDrawingPayload() {
      if (drawingPayloadBuilder_ == null) {
        if (payloadCase_ == 3) {
          payloadCase_ = 0;
          payload_ = null;
          onChanged();
        }
      } else {
        if (payloadCase_ == 3) {
          payloadCase_ = 0;
          payload_ = null;
        }
        drawingPayloadBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.com.xalpol12.websocket.DrawingPayload drawingPayload = 3;</code>
     */
    public com.xalpol12.wsserver.protos.DrawingPayload.Builder getDrawingPayloadBuilder() {
      return getDrawingPayloadFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.xalpol12.websocket.DrawingPayload drawingPayload = 3;</code>
     */
    @java.lang.Override
    public com.xalpol12.wsserver.protos.DrawingPayloadOrBuilder getDrawingPayloadOrBuilder() {
      if ((payloadCase_ == 3) && (drawingPayloadBuilder_ != null)) {
        return drawingPayloadBuilder_.getMessageOrBuilder();
      } else {
        if (payloadCase_ == 3) {
          return (com.xalpol12.wsserver.protos.DrawingPayload) payload_;
        }
        return com.xalpol12.wsserver.protos.DrawingPayload.getDefaultInstance();
      }
    }
    /**
     * <code>.com.xalpol12.websocket.DrawingPayload drawingPayload = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.xalpol12.wsserver.protos.DrawingPayload, com.xalpol12.wsserver.protos.DrawingPayload.Builder, com.xalpol12.wsserver.protos.DrawingPayloadOrBuilder> 
        getDrawingPayloadFieldBuilder() {
      if (drawingPayloadBuilder_ == null) {
        if (!(payloadCase_ == 3)) {
          payload_ = com.xalpol12.wsserver.protos.DrawingPayload.getDefaultInstance();
        }
        drawingPayloadBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.xalpol12.wsserver.protos.DrawingPayload, com.xalpol12.wsserver.protos.DrawingPayload.Builder, com.xalpol12.wsserver.protos.DrawingPayloadOrBuilder>(
                (com.xalpol12.wsserver.protos.DrawingPayload) payload_,
                getParentForChildren(),
                isClean());
        payload_ = null;
      }
      payloadCase_ = 3;
      onChanged();
      return drawingPayloadBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.xalpol12.wsserver.protos.ChatMessagePayload, com.xalpol12.wsserver.protos.ChatMessagePayload.Builder, com.xalpol12.wsserver.protos.ChatMessagePayloadOrBuilder> chatMessagePayloadBuilder_;
    /**
     * <code>.com.xalpol12.websocket.ChatMessagePayload chatMessagePayload = 4;</code>
     * @return Whether the chatMessagePayload field is set.
     */
    @java.lang.Override
    public boolean hasChatMessagePayload() {
      return payloadCase_ == 4;
    }
    /**
     * <code>.com.xalpol12.websocket.ChatMessagePayload chatMessagePayload = 4;</code>
     * @return The chatMessagePayload.
     */
    @java.lang.Override
    public com.xalpol12.wsserver.protos.ChatMessagePayload getChatMessagePayload() {
      if (chatMessagePayloadBuilder_ == null) {
        if (payloadCase_ == 4) {
          return (com.xalpol12.wsserver.protos.ChatMessagePayload) payload_;
        }
        return com.xalpol12.wsserver.protos.ChatMessagePayload.getDefaultInstance();
      } else {
        if (payloadCase_ == 4) {
          return chatMessagePayloadBuilder_.getMessage();
        }
        return com.xalpol12.wsserver.protos.ChatMessagePayload.getDefaultInstance();
      }
    }
    /**
     * <code>.com.xalpol12.websocket.ChatMessagePayload chatMessagePayload = 4;</code>
     */
    public Builder setChatMessagePayload(com.xalpol12.wsserver.protos.ChatMessagePayload value) {
      if (chatMessagePayloadBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        payload_ = value;
        onChanged();
      } else {
        chatMessagePayloadBuilder_.setMessage(value);
      }
      payloadCase_ = 4;
      return this;
    }
    /**
     * <code>.com.xalpol12.websocket.ChatMessagePayload chatMessagePayload = 4;</code>
     */
    public Builder setChatMessagePayload(
        com.xalpol12.wsserver.protos.ChatMessagePayload.Builder builderForValue) {
      if (chatMessagePayloadBuilder_ == null) {
        payload_ = builderForValue.build();
        onChanged();
      } else {
        chatMessagePayloadBuilder_.setMessage(builderForValue.build());
      }
      payloadCase_ = 4;
      return this;
    }
    /**
     * <code>.com.xalpol12.websocket.ChatMessagePayload chatMessagePayload = 4;</code>
     */
    public Builder mergeChatMessagePayload(com.xalpol12.wsserver.protos.ChatMessagePayload value) {
      if (chatMessagePayloadBuilder_ == null) {
        if (payloadCase_ == 4 &&
            payload_ != com.xalpol12.wsserver.protos.ChatMessagePayload.getDefaultInstance()) {
          payload_ = com.xalpol12.wsserver.protos.ChatMessagePayload.newBuilder((com.xalpol12.wsserver.protos.ChatMessagePayload) payload_)
              .mergeFrom(value).buildPartial();
        } else {
          payload_ = value;
        }
        onChanged();
      } else {
        if (payloadCase_ == 4) {
          chatMessagePayloadBuilder_.mergeFrom(value);
        } else {
          chatMessagePayloadBuilder_.setMessage(value);
        }
      }
      payloadCase_ = 4;
      return this;
    }
    /**
     * <code>.com.xalpol12.websocket.ChatMessagePayload chatMessagePayload = 4;</code>
     */
    public Builder clearChatMessagePayload() {
      if (chatMessagePayloadBuilder_ == null) {
        if (payloadCase_ == 4) {
          payloadCase_ = 0;
          payload_ = null;
          onChanged();
        }
      } else {
        if (payloadCase_ == 4) {
          payloadCase_ = 0;
          payload_ = null;
        }
        chatMessagePayloadBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.com.xalpol12.websocket.ChatMessagePayload chatMessagePayload = 4;</code>
     */
    public com.xalpol12.wsserver.protos.ChatMessagePayload.Builder getChatMessagePayloadBuilder() {
      return getChatMessagePayloadFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.xalpol12.websocket.ChatMessagePayload chatMessagePayload = 4;</code>
     */
    @java.lang.Override
    public com.xalpol12.wsserver.protos.ChatMessagePayloadOrBuilder getChatMessagePayloadOrBuilder() {
      if ((payloadCase_ == 4) && (chatMessagePayloadBuilder_ != null)) {
        return chatMessagePayloadBuilder_.getMessageOrBuilder();
      } else {
        if (payloadCase_ == 4) {
          return (com.xalpol12.wsserver.protos.ChatMessagePayload) payload_;
        }
        return com.xalpol12.wsserver.protos.ChatMessagePayload.getDefaultInstance();
      }
    }
    /**
     * <code>.com.xalpol12.websocket.ChatMessagePayload chatMessagePayload = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.xalpol12.wsserver.protos.ChatMessagePayload, com.xalpol12.wsserver.protos.ChatMessagePayload.Builder, com.xalpol12.wsserver.protos.ChatMessagePayloadOrBuilder> 
        getChatMessagePayloadFieldBuilder() {
      if (chatMessagePayloadBuilder_ == null) {
        if (!(payloadCase_ == 4)) {
          payload_ = com.xalpol12.wsserver.protos.ChatMessagePayload.getDefaultInstance();
        }
        chatMessagePayloadBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.xalpol12.wsserver.protos.ChatMessagePayload, com.xalpol12.wsserver.protos.ChatMessagePayload.Builder, com.xalpol12.wsserver.protos.ChatMessagePayloadOrBuilder>(
                (com.xalpol12.wsserver.protos.ChatMessagePayload) payload_,
                getParentForChildren(),
                isClean());
        payload_ = null;
      }
      payloadCase_ = 4;
      onChanged();
      return chatMessagePayloadBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.xalpol12.wsserver.protos.GameTimerPayload, com.xalpol12.wsserver.protos.GameTimerPayload.Builder, com.xalpol12.wsserver.protos.GameTimerPayloadOrBuilder> gameTimerPayloadBuilder_;
    /**
     * <code>.com.xalpol12.websocket.GameTimerPayload gameTimerPayload = 5;</code>
     * @return Whether the gameTimerPayload field is set.
     */
    @java.lang.Override
    public boolean hasGameTimerPayload() {
      return payloadCase_ == 5;
    }
    /**
     * <code>.com.xalpol12.websocket.GameTimerPayload gameTimerPayload = 5;</code>
     * @return The gameTimerPayload.
     */
    @java.lang.Override
    public com.xalpol12.wsserver.protos.GameTimerPayload getGameTimerPayload() {
      if (gameTimerPayloadBuilder_ == null) {
        if (payloadCase_ == 5) {
          return (com.xalpol12.wsserver.protos.GameTimerPayload) payload_;
        }
        return com.xalpol12.wsserver.protos.GameTimerPayload.getDefaultInstance();
      } else {
        if (payloadCase_ == 5) {
          return gameTimerPayloadBuilder_.getMessage();
        }
        return com.xalpol12.wsserver.protos.GameTimerPayload.getDefaultInstance();
      }
    }
    /**
     * <code>.com.xalpol12.websocket.GameTimerPayload gameTimerPayload = 5;</code>
     */
    public Builder setGameTimerPayload(com.xalpol12.wsserver.protos.GameTimerPayload value) {
      if (gameTimerPayloadBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        payload_ = value;
        onChanged();
      } else {
        gameTimerPayloadBuilder_.setMessage(value);
      }
      payloadCase_ = 5;
      return this;
    }
    /**
     * <code>.com.xalpol12.websocket.GameTimerPayload gameTimerPayload = 5;</code>
     */
    public Builder setGameTimerPayload(
        com.xalpol12.wsserver.protos.GameTimerPayload.Builder builderForValue) {
      if (gameTimerPayloadBuilder_ == null) {
        payload_ = builderForValue.build();
        onChanged();
      } else {
        gameTimerPayloadBuilder_.setMessage(builderForValue.build());
      }
      payloadCase_ = 5;
      return this;
    }
    /**
     * <code>.com.xalpol12.websocket.GameTimerPayload gameTimerPayload = 5;</code>
     */
    public Builder mergeGameTimerPayload(com.xalpol12.wsserver.protos.GameTimerPayload value) {
      if (gameTimerPayloadBuilder_ == null) {
        if (payloadCase_ == 5 &&
            payload_ != com.xalpol12.wsserver.protos.GameTimerPayload.getDefaultInstance()) {
          payload_ = com.xalpol12.wsserver.protos.GameTimerPayload.newBuilder((com.xalpol12.wsserver.protos.GameTimerPayload) payload_)
              .mergeFrom(value).buildPartial();
        } else {
          payload_ = value;
        }
        onChanged();
      } else {
        if (payloadCase_ == 5) {
          gameTimerPayloadBuilder_.mergeFrom(value);
        } else {
          gameTimerPayloadBuilder_.setMessage(value);
        }
      }
      payloadCase_ = 5;
      return this;
    }
    /**
     * <code>.com.xalpol12.websocket.GameTimerPayload gameTimerPayload = 5;</code>
     */
    public Builder clearGameTimerPayload() {
      if (gameTimerPayloadBuilder_ == null) {
        if (payloadCase_ == 5) {
          payloadCase_ = 0;
          payload_ = null;
          onChanged();
        }
      } else {
        if (payloadCase_ == 5) {
          payloadCase_ = 0;
          payload_ = null;
        }
        gameTimerPayloadBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.com.xalpol12.websocket.GameTimerPayload gameTimerPayload = 5;</code>
     */
    public com.xalpol12.wsserver.protos.GameTimerPayload.Builder getGameTimerPayloadBuilder() {
      return getGameTimerPayloadFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.xalpol12.websocket.GameTimerPayload gameTimerPayload = 5;</code>
     */
    @java.lang.Override
    public com.xalpol12.wsserver.protos.GameTimerPayloadOrBuilder getGameTimerPayloadOrBuilder() {
      if ((payloadCase_ == 5) && (gameTimerPayloadBuilder_ != null)) {
        return gameTimerPayloadBuilder_.getMessageOrBuilder();
      } else {
        if (payloadCase_ == 5) {
          return (com.xalpol12.wsserver.protos.GameTimerPayload) payload_;
        }
        return com.xalpol12.wsserver.protos.GameTimerPayload.getDefaultInstance();
      }
    }
    /**
     * <code>.com.xalpol12.websocket.GameTimerPayload gameTimerPayload = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.xalpol12.wsserver.protos.GameTimerPayload, com.xalpol12.wsserver.protos.GameTimerPayload.Builder, com.xalpol12.wsserver.protos.GameTimerPayloadOrBuilder> 
        getGameTimerPayloadFieldBuilder() {
      if (gameTimerPayloadBuilder_ == null) {
        if (!(payloadCase_ == 5)) {
          payload_ = com.xalpol12.wsserver.protos.GameTimerPayload.getDefaultInstance();
        }
        gameTimerPayloadBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.xalpol12.wsserver.protos.GameTimerPayload, com.xalpol12.wsserver.protos.GameTimerPayload.Builder, com.xalpol12.wsserver.protos.GameTimerPayloadOrBuilder>(
                (com.xalpol12.wsserver.protos.GameTimerPayload) payload_,
                getParentForChildren(),
                isClean());
        payload_ = null;
      }
      payloadCase_ = 5;
      onChanged();
      return gameTimerPayloadBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.xalpol12.wsserver.protos.NewWordPayload, com.xalpol12.wsserver.protos.NewWordPayload.Builder, com.xalpol12.wsserver.protos.NewWordPayloadOrBuilder> newWordPayloadBuilder_;
    /**
     * <code>.com.xalpol12.websocket.NewWordPayload newWordPayload = 6;</code>
     * @return Whether the newWordPayload field is set.
     */
    @java.lang.Override
    public boolean hasNewWordPayload() {
      return payloadCase_ == 6;
    }
    /**
     * <code>.com.xalpol12.websocket.NewWordPayload newWordPayload = 6;</code>
     * @return The newWordPayload.
     */
    @java.lang.Override
    public com.xalpol12.wsserver.protos.NewWordPayload getNewWordPayload() {
      if (newWordPayloadBuilder_ == null) {
        if (payloadCase_ == 6) {
          return (com.xalpol12.wsserver.protos.NewWordPayload) payload_;
        }
        return com.xalpol12.wsserver.protos.NewWordPayload.getDefaultInstance();
      } else {
        if (payloadCase_ == 6) {
          return newWordPayloadBuilder_.getMessage();
        }
        return com.xalpol12.wsserver.protos.NewWordPayload.getDefaultInstance();
      }
    }
    /**
     * <code>.com.xalpol12.websocket.NewWordPayload newWordPayload = 6;</code>
     */
    public Builder setNewWordPayload(com.xalpol12.wsserver.protos.NewWordPayload value) {
      if (newWordPayloadBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        payload_ = value;
        onChanged();
      } else {
        newWordPayloadBuilder_.setMessage(value);
      }
      payloadCase_ = 6;
      return this;
    }
    /**
     * <code>.com.xalpol12.websocket.NewWordPayload newWordPayload = 6;</code>
     */
    public Builder setNewWordPayload(
        com.xalpol12.wsserver.protos.NewWordPayload.Builder builderForValue) {
      if (newWordPayloadBuilder_ == null) {
        payload_ = builderForValue.build();
        onChanged();
      } else {
        newWordPayloadBuilder_.setMessage(builderForValue.build());
      }
      payloadCase_ = 6;
      return this;
    }
    /**
     * <code>.com.xalpol12.websocket.NewWordPayload newWordPayload = 6;</code>
     */
    public Builder mergeNewWordPayload(com.xalpol12.wsserver.protos.NewWordPayload value) {
      if (newWordPayloadBuilder_ == null) {
        if (payloadCase_ == 6 &&
            payload_ != com.xalpol12.wsserver.protos.NewWordPayload.getDefaultInstance()) {
          payload_ = com.xalpol12.wsserver.protos.NewWordPayload.newBuilder((com.xalpol12.wsserver.protos.NewWordPayload) payload_)
              .mergeFrom(value).buildPartial();
        } else {
          payload_ = value;
        }
        onChanged();
      } else {
        if (payloadCase_ == 6) {
          newWordPayloadBuilder_.mergeFrom(value);
        } else {
          newWordPayloadBuilder_.setMessage(value);
        }
      }
      payloadCase_ = 6;
      return this;
    }
    /**
     * <code>.com.xalpol12.websocket.NewWordPayload newWordPayload = 6;</code>
     */
    public Builder clearNewWordPayload() {
      if (newWordPayloadBuilder_ == null) {
        if (payloadCase_ == 6) {
          payloadCase_ = 0;
          payload_ = null;
          onChanged();
        }
      } else {
        if (payloadCase_ == 6) {
          payloadCase_ = 0;
          payload_ = null;
        }
        newWordPayloadBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.com.xalpol12.websocket.NewWordPayload newWordPayload = 6;</code>
     */
    public com.xalpol12.wsserver.protos.NewWordPayload.Builder getNewWordPayloadBuilder() {
      return getNewWordPayloadFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.xalpol12.websocket.NewWordPayload newWordPayload = 6;</code>
     */
    @java.lang.Override
    public com.xalpol12.wsserver.protos.NewWordPayloadOrBuilder getNewWordPayloadOrBuilder() {
      if ((payloadCase_ == 6) && (newWordPayloadBuilder_ != null)) {
        return newWordPayloadBuilder_.getMessageOrBuilder();
      } else {
        if (payloadCase_ == 6) {
          return (com.xalpol12.wsserver.protos.NewWordPayload) payload_;
        }
        return com.xalpol12.wsserver.protos.NewWordPayload.getDefaultInstance();
      }
    }
    /**
     * <code>.com.xalpol12.websocket.NewWordPayload newWordPayload = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.xalpol12.wsserver.protos.NewWordPayload, com.xalpol12.wsserver.protos.NewWordPayload.Builder, com.xalpol12.wsserver.protos.NewWordPayloadOrBuilder> 
        getNewWordPayloadFieldBuilder() {
      if (newWordPayloadBuilder_ == null) {
        if (!(payloadCase_ == 6)) {
          payload_ = com.xalpol12.wsserver.protos.NewWordPayload.getDefaultInstance();
        }
        newWordPayloadBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.xalpol12.wsserver.protos.NewWordPayload, com.xalpol12.wsserver.protos.NewWordPayload.Builder, com.xalpol12.wsserver.protos.NewWordPayloadOrBuilder>(
                (com.xalpol12.wsserver.protos.NewWordPayload) payload_,
                getParentForChildren(),
                isClean());
        payload_ = null;
      }
      payloadCase_ = 6;
      onChanged();
      return newWordPayloadBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.xalpol12.wsserver.protos.GameScorePayload, com.xalpol12.wsserver.protos.GameScorePayload.Builder, com.xalpol12.wsserver.protos.GameScorePayloadOrBuilder> gameScorePayloadBuilder_;
    /**
     * <code>.com.xalpol12.websocket.GameScorePayload gameScorePayload = 7;</code>
     * @return Whether the gameScorePayload field is set.
     */
    @java.lang.Override
    public boolean hasGameScorePayload() {
      return payloadCase_ == 7;
    }
    /**
     * <code>.com.xalpol12.websocket.GameScorePayload gameScorePayload = 7;</code>
     * @return The gameScorePayload.
     */
    @java.lang.Override
    public com.xalpol12.wsserver.protos.GameScorePayload getGameScorePayload() {
      if (gameScorePayloadBuilder_ == null) {
        if (payloadCase_ == 7) {
          return (com.xalpol12.wsserver.protos.GameScorePayload) payload_;
        }
        return com.xalpol12.wsserver.protos.GameScorePayload.getDefaultInstance();
      } else {
        if (payloadCase_ == 7) {
          return gameScorePayloadBuilder_.getMessage();
        }
        return com.xalpol12.wsserver.protos.GameScorePayload.getDefaultInstance();
      }
    }
    /**
     * <code>.com.xalpol12.websocket.GameScorePayload gameScorePayload = 7;</code>
     */
    public Builder setGameScorePayload(com.xalpol12.wsserver.protos.GameScorePayload value) {
      if (gameScorePayloadBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        payload_ = value;
        onChanged();
      } else {
        gameScorePayloadBuilder_.setMessage(value);
      }
      payloadCase_ = 7;
      return this;
    }
    /**
     * <code>.com.xalpol12.websocket.GameScorePayload gameScorePayload = 7;</code>
     */
    public Builder setGameScorePayload(
        com.xalpol12.wsserver.protos.GameScorePayload.Builder builderForValue) {
      if (gameScorePayloadBuilder_ == null) {
        payload_ = builderForValue.build();
        onChanged();
      } else {
        gameScorePayloadBuilder_.setMessage(builderForValue.build());
      }
      payloadCase_ = 7;
      return this;
    }
    /**
     * <code>.com.xalpol12.websocket.GameScorePayload gameScorePayload = 7;</code>
     */
    public Builder mergeGameScorePayload(com.xalpol12.wsserver.protos.GameScorePayload value) {
      if (gameScorePayloadBuilder_ == null) {
        if (payloadCase_ == 7 &&
            payload_ != com.xalpol12.wsserver.protos.GameScorePayload.getDefaultInstance()) {
          payload_ = com.xalpol12.wsserver.protos.GameScorePayload.newBuilder((com.xalpol12.wsserver.protos.GameScorePayload) payload_)
              .mergeFrom(value).buildPartial();
        } else {
          payload_ = value;
        }
        onChanged();
      } else {
        if (payloadCase_ == 7) {
          gameScorePayloadBuilder_.mergeFrom(value);
        } else {
          gameScorePayloadBuilder_.setMessage(value);
        }
      }
      payloadCase_ = 7;
      return this;
    }
    /**
     * <code>.com.xalpol12.websocket.GameScorePayload gameScorePayload = 7;</code>
     */
    public Builder clearGameScorePayload() {
      if (gameScorePayloadBuilder_ == null) {
        if (payloadCase_ == 7) {
          payloadCase_ = 0;
          payload_ = null;
          onChanged();
        }
      } else {
        if (payloadCase_ == 7) {
          payloadCase_ = 0;
          payload_ = null;
        }
        gameScorePayloadBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.com.xalpol12.websocket.GameScorePayload gameScorePayload = 7;</code>
     */
    public com.xalpol12.wsserver.protos.GameScorePayload.Builder getGameScorePayloadBuilder() {
      return getGameScorePayloadFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.xalpol12.websocket.GameScorePayload gameScorePayload = 7;</code>
     */
    @java.lang.Override
    public com.xalpol12.wsserver.protos.GameScorePayloadOrBuilder getGameScorePayloadOrBuilder() {
      if ((payloadCase_ == 7) && (gameScorePayloadBuilder_ != null)) {
        return gameScorePayloadBuilder_.getMessageOrBuilder();
      } else {
        if (payloadCase_ == 7) {
          return (com.xalpol12.wsserver.protos.GameScorePayload) payload_;
        }
        return com.xalpol12.wsserver.protos.GameScorePayload.getDefaultInstance();
      }
    }
    /**
     * <code>.com.xalpol12.websocket.GameScorePayload gameScorePayload = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.xalpol12.wsserver.protos.GameScorePayload, com.xalpol12.wsserver.protos.GameScorePayload.Builder, com.xalpol12.wsserver.protos.GameScorePayloadOrBuilder> 
        getGameScorePayloadFieldBuilder() {
      if (gameScorePayloadBuilder_ == null) {
        if (!(payloadCase_ == 7)) {
          payload_ = com.xalpol12.wsserver.protos.GameScorePayload.getDefaultInstance();
        }
        gameScorePayloadBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.xalpol12.wsserver.protos.GameScorePayload, com.xalpol12.wsserver.protos.GameScorePayload.Builder, com.xalpol12.wsserver.protos.GameScorePayloadOrBuilder>(
                (com.xalpol12.wsserver.protos.GameScorePayload) payload_,
                getParentForChildren(),
                isClean());
        payload_ = null;
      }
      payloadCase_ = 7;
      onChanged();
      return gameScorePayloadBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.xalpol12.wsserver.protos.ClearBoardPayload, com.xalpol12.wsserver.protos.ClearBoardPayload.Builder, com.xalpol12.wsserver.protos.ClearBoardPayloadOrBuilder> clearBoardPayloadBuilder_;
    /**
     * <code>.com.xalpol12.websocket.ClearBoardPayload clearBoardPayload = 8;</code>
     * @return Whether the clearBoardPayload field is set.
     */
    @java.lang.Override
    public boolean hasClearBoardPayload() {
      return payloadCase_ == 8;
    }
    /**
     * <code>.com.xalpol12.websocket.ClearBoardPayload clearBoardPayload = 8;</code>
     * @return The clearBoardPayload.
     */
    @java.lang.Override
    public com.xalpol12.wsserver.protos.ClearBoardPayload getClearBoardPayload() {
      if (clearBoardPayloadBuilder_ == null) {
        if (payloadCase_ == 8) {
          return (com.xalpol12.wsserver.protos.ClearBoardPayload) payload_;
        }
        return com.xalpol12.wsserver.protos.ClearBoardPayload.getDefaultInstance();
      } else {
        if (payloadCase_ == 8) {
          return clearBoardPayloadBuilder_.getMessage();
        }
        return com.xalpol12.wsserver.protos.ClearBoardPayload.getDefaultInstance();
      }
    }
    /**
     * <code>.com.xalpol12.websocket.ClearBoardPayload clearBoardPayload = 8;</code>
     */
    public Builder setClearBoardPayload(com.xalpol12.wsserver.protos.ClearBoardPayload value) {
      if (clearBoardPayloadBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        payload_ = value;
        onChanged();
      } else {
        clearBoardPayloadBuilder_.setMessage(value);
      }
      payloadCase_ = 8;
      return this;
    }
    /**
     * <code>.com.xalpol12.websocket.ClearBoardPayload clearBoardPayload = 8;</code>
     */
    public Builder setClearBoardPayload(
        com.xalpol12.wsserver.protos.ClearBoardPayload.Builder builderForValue) {
      if (clearBoardPayloadBuilder_ == null) {
        payload_ = builderForValue.build();
        onChanged();
      } else {
        clearBoardPayloadBuilder_.setMessage(builderForValue.build());
      }
      payloadCase_ = 8;
      return this;
    }
    /**
     * <code>.com.xalpol12.websocket.ClearBoardPayload clearBoardPayload = 8;</code>
     */
    public Builder mergeClearBoardPayload(com.xalpol12.wsserver.protos.ClearBoardPayload value) {
      if (clearBoardPayloadBuilder_ == null) {
        if (payloadCase_ == 8 &&
            payload_ != com.xalpol12.wsserver.protos.ClearBoardPayload.getDefaultInstance()) {
          payload_ = com.xalpol12.wsserver.protos.ClearBoardPayload.newBuilder((com.xalpol12.wsserver.protos.ClearBoardPayload) payload_)
              .mergeFrom(value).buildPartial();
        } else {
          payload_ = value;
        }
        onChanged();
      } else {
        if (payloadCase_ == 8) {
          clearBoardPayloadBuilder_.mergeFrom(value);
        } else {
          clearBoardPayloadBuilder_.setMessage(value);
        }
      }
      payloadCase_ = 8;
      return this;
    }
    /**
     * <code>.com.xalpol12.websocket.ClearBoardPayload clearBoardPayload = 8;</code>
     */
    public Builder clearClearBoardPayload() {
      if (clearBoardPayloadBuilder_ == null) {
        if (payloadCase_ == 8) {
          payloadCase_ = 0;
          payload_ = null;
          onChanged();
        }
      } else {
        if (payloadCase_ == 8) {
          payloadCase_ = 0;
          payload_ = null;
        }
        clearBoardPayloadBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.com.xalpol12.websocket.ClearBoardPayload clearBoardPayload = 8;</code>
     */
    public com.xalpol12.wsserver.protos.ClearBoardPayload.Builder getClearBoardPayloadBuilder() {
      return getClearBoardPayloadFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.xalpol12.websocket.ClearBoardPayload clearBoardPayload = 8;</code>
     */
    @java.lang.Override
    public com.xalpol12.wsserver.protos.ClearBoardPayloadOrBuilder getClearBoardPayloadOrBuilder() {
      if ((payloadCase_ == 8) && (clearBoardPayloadBuilder_ != null)) {
        return clearBoardPayloadBuilder_.getMessageOrBuilder();
      } else {
        if (payloadCase_ == 8) {
          return (com.xalpol12.wsserver.protos.ClearBoardPayload) payload_;
        }
        return com.xalpol12.wsserver.protos.ClearBoardPayload.getDefaultInstance();
      }
    }
    /**
     * <code>.com.xalpol12.websocket.ClearBoardPayload clearBoardPayload = 8;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.xalpol12.wsserver.protos.ClearBoardPayload, com.xalpol12.wsserver.protos.ClearBoardPayload.Builder, com.xalpol12.wsserver.protos.ClearBoardPayloadOrBuilder> 
        getClearBoardPayloadFieldBuilder() {
      if (clearBoardPayloadBuilder_ == null) {
        if (!(payloadCase_ == 8)) {
          payload_ = com.xalpol12.wsserver.protos.ClearBoardPayload.getDefaultInstance();
        }
        clearBoardPayloadBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.xalpol12.wsserver.protos.ClearBoardPayload, com.xalpol12.wsserver.protos.ClearBoardPayload.Builder, com.xalpol12.wsserver.protos.ClearBoardPayloadOrBuilder>(
                (com.xalpol12.wsserver.protos.ClearBoardPayload) payload_,
                getParentForChildren(),
                isClean());
        payload_ = null;
      }
      payloadCase_ = 8;
      onChanged();
      return clearBoardPayloadBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.xalpol12.websocket.CustomMessage)
  }

  // @@protoc_insertion_point(class_scope:com.xalpol12.websocket.CustomMessage)
  private static final com.xalpol12.wsserver.protos.CustomMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.xalpol12.wsserver.protos.CustomMessage();
  }

  public static com.xalpol12.wsserver.protos.CustomMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CustomMessage>
      PARSER = new com.google.protobuf.AbstractParser<CustomMessage>() {
    @java.lang.Override
    public CustomMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CustomMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CustomMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.xalpol12.wsserver.protos.CustomMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

