// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

package com.xalpol12.wsserver.protos;

public final class CustomMessageProtos {
  private CustomMessageProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xalpol12_websocket_CustomMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xalpol12_websocket_CustomMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xalpol12_websocket_HandshakePayload_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xalpol12_websocket_HandshakePayload_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xalpol12_websocket_DrawingPayload_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xalpol12_websocket_DrawingPayload_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xalpol12_websocket_ChatMessagePayload_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xalpol12_websocket_ChatMessagePayload_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xalpol12_websocket_GameTimerPayload_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xalpol12_websocket_GameTimerPayload_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xalpol12_websocket_NewWordPayload_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xalpol12_websocket_NewWordPayload_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xalpol12_websocket_GameScorePayload_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xalpol12_websocket_GameScorePayload_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xalpol12_websocket_ClearBoardPayload_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xalpol12_websocket_ClearBoardPayload_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016messages.proto\022\026com.xalpol12.websocket" +
      "\"\274\004\n\rCustomMessage\0228\n\013messageType\030\001 \001(\0162" +
      "#.com.xalpol12.websocket.MessageType\022D\n\020" +
      "HandshakePayload\030\002 \001(\0132(.com.xalpol12.we" +
      "bsocket.HandshakePayloadH\000\022@\n\016drawingPay" +
      "load\030\003 \001(\0132&.com.xalpol12.websocket.Draw" +
      "ingPayloadH\000\022H\n\022chatMessagePayload\030\004 \001(\013" +
      "2*.com.xalpol12.websocket.ChatMessagePay" +
      "loadH\000\022D\n\020gameTimerPayload\030\005 \001(\0132(.com.x" +
      "alpol12.websocket.GameTimerPayloadH\000\022@\n\016" +
      "newWordPayload\030\006 \001(\0132&.com.xalpol12.webs" +
      "ocket.NewWordPayloadH\000\022D\n\020gameScorePaylo" +
      "ad\030\007 \001(\0132(.com.xalpol12.websocket.GameSc" +
      "orePayloadH\000\022F\n\021clearBoardPayload\030\010 \001(\0132" +
      ").com.xalpol12.websocket.ClearBoardPaylo" +
      "adH\000B\t\n\007payload\"5\n\020HandshakePayload\022\016\n\006u" +
      "serId\030\001 \001(\t\022\021\n\tsessionId\030\002 \001(\t\"&\n\016Drawin" +
      "gPayload\022\024\n\014drawingFrame\030\001 \001(\t\"5\n\022ChatMe" +
      "ssagePayload\022\016\n\006sender\030\001 \001(\t\022\017\n\007content\030" +
      "\002 \001(\t\" \n\020GameTimerPayload\022\014\n\004time\030\001 \001(\005\"" +
      "4\n\016NewWordPayload\022\017\n\007newWord\030\001 \001(\t\022\021\n\tne" +
      "wDrawer\030\002 \001(\t\"1\n\020GameScorePayload\022\016\n\006use" +
      "rId\030\001 \001(\t\022\r\n\005score\030\002 \001(\005\"&\n\021ClearBoardPa" +
      "yload\022\021\n\tsessionId\030\001 \001(\t*z\n\013MessageType\022" +
      "\r\n\tHANDSHAKE\020\000\022\013\n\007DRAWING\020\001\022\020\n\014CHAT_MESS" +
      "AGE\020\002\022\016\n\nGAME_TIMER\020\003\022\014\n\010NEW_WORD\020\004\022\016\n\nG" +
      "AME_SCORE\020\005\022\017\n\013CLEAR_BOARD\020\006B5\n\034com.xalp" +
      "ol12.wsserver.protosB\023CustomMessageProto" +
      "sP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_xalpol12_websocket_CustomMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_xalpol12_websocket_CustomMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xalpol12_websocket_CustomMessage_descriptor,
        new java.lang.String[] { "MessageType", "HandshakePayload", "DrawingPayload", "ChatMessagePayload", "GameTimerPayload", "NewWordPayload", "GameScorePayload", "ClearBoardPayload", "Payload", });
    internal_static_com_xalpol12_websocket_HandshakePayload_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_xalpol12_websocket_HandshakePayload_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xalpol12_websocket_HandshakePayload_descriptor,
        new java.lang.String[] { "UserId", "SessionId", });
    internal_static_com_xalpol12_websocket_DrawingPayload_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_xalpol12_websocket_DrawingPayload_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xalpol12_websocket_DrawingPayload_descriptor,
        new java.lang.String[] { "DrawingFrame", });
    internal_static_com_xalpol12_websocket_ChatMessagePayload_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_xalpol12_websocket_ChatMessagePayload_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xalpol12_websocket_ChatMessagePayload_descriptor,
        new java.lang.String[] { "Sender", "Content", });
    internal_static_com_xalpol12_websocket_GameTimerPayload_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_xalpol12_websocket_GameTimerPayload_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xalpol12_websocket_GameTimerPayload_descriptor,
        new java.lang.String[] { "Time", });
    internal_static_com_xalpol12_websocket_NewWordPayload_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_xalpol12_websocket_NewWordPayload_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xalpol12_websocket_NewWordPayload_descriptor,
        new java.lang.String[] { "NewWord", "NewDrawer", });
    internal_static_com_xalpol12_websocket_GameScorePayload_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_com_xalpol12_websocket_GameScorePayload_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xalpol12_websocket_GameScorePayload_descriptor,
        new java.lang.String[] { "UserId", "Score", });
    internal_static_com_xalpol12_websocket_ClearBoardPayload_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_com_xalpol12_websocket_ClearBoardPayload_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xalpol12_websocket_ClearBoardPayload_descriptor,
        new java.lang.String[] { "SessionId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
