// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

package com.xalpol12.wsserver.protos;

public interface CustomMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.xalpol12.websocket.CustomMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.xalpol12.websocket.MessageType messageType = 1;</code>
   * @return The enum numeric value on the wire for messageType.
   */
  int getMessageTypeValue();
  /**
   * <code>.com.xalpol12.websocket.MessageType messageType = 1;</code>
   * @return The messageType.
   */
  com.xalpol12.wsserver.protos.MessageType getMessageType();

  /**
   * <code>.com.xalpol12.websocket.HandshakePayload HandshakePayload = 2;</code>
   * @return Whether the handshakePayload field is set.
   */
  boolean hasHandshakePayload();
  /**
   * <code>.com.xalpol12.websocket.HandshakePayload HandshakePayload = 2;</code>
   * @return The handshakePayload.
   */
  com.xalpol12.wsserver.protos.HandshakePayload getHandshakePayload();
  /**
   * <code>.com.xalpol12.websocket.HandshakePayload HandshakePayload = 2;</code>
   */
  com.xalpol12.wsserver.protos.HandshakePayloadOrBuilder getHandshakePayloadOrBuilder();

  /**
   * <code>.com.xalpol12.websocket.DrawingPayload drawingPayload = 3;</code>
   * @return Whether the drawingPayload field is set.
   */
  boolean hasDrawingPayload();
  /**
   * <code>.com.xalpol12.websocket.DrawingPayload drawingPayload = 3;</code>
   * @return The drawingPayload.
   */
  com.xalpol12.wsserver.protos.DrawingPayload getDrawingPayload();
  /**
   * <code>.com.xalpol12.websocket.DrawingPayload drawingPayload = 3;</code>
   */
  com.xalpol12.wsserver.protos.DrawingPayloadOrBuilder getDrawingPayloadOrBuilder();

  /**
   * <code>.com.xalpol12.websocket.ChatMessagePayload chatMessagePayload = 4;</code>
   * @return Whether the chatMessagePayload field is set.
   */
  boolean hasChatMessagePayload();
  /**
   * <code>.com.xalpol12.websocket.ChatMessagePayload chatMessagePayload = 4;</code>
   * @return The chatMessagePayload.
   */
  com.xalpol12.wsserver.protos.ChatMessagePayload getChatMessagePayload();
  /**
   * <code>.com.xalpol12.websocket.ChatMessagePayload chatMessagePayload = 4;</code>
   */
  com.xalpol12.wsserver.protos.ChatMessagePayloadOrBuilder getChatMessagePayloadOrBuilder();

  /**
   * <code>.com.xalpol12.websocket.GameTimerPayload gameTimerPayload = 5;</code>
   * @return Whether the gameTimerPayload field is set.
   */
  boolean hasGameTimerPayload();
  /**
   * <code>.com.xalpol12.websocket.GameTimerPayload gameTimerPayload = 5;</code>
   * @return The gameTimerPayload.
   */
  com.xalpol12.wsserver.protos.GameTimerPayload getGameTimerPayload();
  /**
   * <code>.com.xalpol12.websocket.GameTimerPayload gameTimerPayload = 5;</code>
   */
  com.xalpol12.wsserver.protos.GameTimerPayloadOrBuilder getGameTimerPayloadOrBuilder();

  /**
   * <code>.com.xalpol12.websocket.NewWordPayload newWordPayload = 6;</code>
   * @return Whether the newWordPayload field is set.
   */
  boolean hasNewWordPayload();
  /**
   * <code>.com.xalpol12.websocket.NewWordPayload newWordPayload = 6;</code>
   * @return The newWordPayload.
   */
  com.xalpol12.wsserver.protos.NewWordPayload getNewWordPayload();
  /**
   * <code>.com.xalpol12.websocket.NewWordPayload newWordPayload = 6;</code>
   */
  com.xalpol12.wsserver.protos.NewWordPayloadOrBuilder getNewWordPayloadOrBuilder();

  /**
   * <code>.com.xalpol12.websocket.GameScorePayload gameScorePayload = 7;</code>
   * @return Whether the gameScorePayload field is set.
   */
  boolean hasGameScorePayload();
  /**
   * <code>.com.xalpol12.websocket.GameScorePayload gameScorePayload = 7;</code>
   * @return The gameScorePayload.
   */
  com.xalpol12.wsserver.protos.GameScorePayload getGameScorePayload();
  /**
   * <code>.com.xalpol12.websocket.GameScorePayload gameScorePayload = 7;</code>
   */
  com.xalpol12.wsserver.protos.GameScorePayloadOrBuilder getGameScorePayloadOrBuilder();

  /**
   * <code>.com.xalpol12.websocket.ClearBoardPayload clearBoardPayload = 8;</code>
   * @return Whether the clearBoardPayload field is set.
   */
  boolean hasClearBoardPayload();
  /**
   * <code>.com.xalpol12.websocket.ClearBoardPayload clearBoardPayload = 8;</code>
   * @return The clearBoardPayload.
   */
  com.xalpol12.wsserver.protos.ClearBoardPayload getClearBoardPayload();
  /**
   * <code>.com.xalpol12.websocket.ClearBoardPayload clearBoardPayload = 8;</code>
   */
  com.xalpol12.wsserver.protos.ClearBoardPayloadOrBuilder getClearBoardPayloadOrBuilder();

  public com.xalpol12.wsserver.protos.CustomMessage.PayloadCase getPayloadCase();
}
