// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

package com.xalpol12.wsserver.protos;

public interface DrawingPayloadOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.xalpol12.websocket.DrawingPayload)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string drawingFrame = 1;</code>
   * @return The drawingFrame.
   */
  java.lang.String getDrawingFrame();
  /**
   * <code>string drawingFrame = 1;</code>
   * @return The bytes for drawingFrame.
   */
  com.google.protobuf.ByteString
      getDrawingFrameBytes();
}
