// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

package com.xalpol12.wsserver.protos;

/**
 * Protobuf type {@code com.xalpol12.websocket.DrawingPayload}
 */
public final class DrawingPayload extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.xalpol12.websocket.DrawingPayload)
    DrawingPayloadOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DrawingPayload.newBuilder() to construct.
  private DrawingPayload(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DrawingPayload() {
    drawingFrame_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new DrawingPayload();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.xalpol12.wsserver.protos.CustomMessageProtos.internal_static_com_xalpol12_websocket_DrawingPayload_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.xalpol12.wsserver.protos.CustomMessageProtos.internal_static_com_xalpol12_websocket_DrawingPayload_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.xalpol12.wsserver.protos.DrawingPayload.class, com.xalpol12.wsserver.protos.DrawingPayload.Builder.class);
  }

  public static final int DRAWINGFRAME_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object drawingFrame_ = "";
  /**
   * <code>string drawingFrame = 1;</code>
   * @return The drawingFrame.
   */
  @java.lang.Override
  public java.lang.String getDrawingFrame() {
    java.lang.Object ref = drawingFrame_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      drawingFrame_ = s;
      return s;
    }
  }
  /**
   * <code>string drawingFrame = 1;</code>
   * @return The bytes for drawingFrame.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDrawingFrameBytes() {
    java.lang.Object ref = drawingFrame_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      drawingFrame_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(drawingFrame_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, drawingFrame_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(drawingFrame_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, drawingFrame_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.xalpol12.wsserver.protos.DrawingPayload)) {
      return super.equals(obj);
    }
    com.xalpol12.wsserver.protos.DrawingPayload other = (com.xalpol12.wsserver.protos.DrawingPayload) obj;

    if (!getDrawingFrame()
        .equals(other.getDrawingFrame())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DRAWINGFRAME_FIELD_NUMBER;
    hash = (53 * hash) + getDrawingFrame().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.xalpol12.wsserver.protos.DrawingPayload parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xalpol12.wsserver.protos.DrawingPayload parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xalpol12.wsserver.protos.DrawingPayload parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xalpol12.wsserver.protos.DrawingPayload parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xalpol12.wsserver.protos.DrawingPayload parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xalpol12.wsserver.protos.DrawingPayload parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xalpol12.wsserver.protos.DrawingPayload parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xalpol12.wsserver.protos.DrawingPayload parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.xalpol12.wsserver.protos.DrawingPayload parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.xalpol12.wsserver.protos.DrawingPayload parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.xalpol12.wsserver.protos.DrawingPayload parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xalpol12.wsserver.protos.DrawingPayload parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.xalpol12.wsserver.protos.DrawingPayload prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.xalpol12.websocket.DrawingPayload}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.xalpol12.websocket.DrawingPayload)
      com.xalpol12.wsserver.protos.DrawingPayloadOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xalpol12.wsserver.protos.CustomMessageProtos.internal_static_com_xalpol12_websocket_DrawingPayload_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xalpol12.wsserver.protos.CustomMessageProtos.internal_static_com_xalpol12_websocket_DrawingPayload_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xalpol12.wsserver.protos.DrawingPayload.class, com.xalpol12.wsserver.protos.DrawingPayload.Builder.class);
    }

    // Construct using com.xalpol12.wsserver.protos.DrawingPayload.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      drawingFrame_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.xalpol12.wsserver.protos.CustomMessageProtos.internal_static_com_xalpol12_websocket_DrawingPayload_descriptor;
    }

    @java.lang.Override
    public com.xalpol12.wsserver.protos.DrawingPayload getDefaultInstanceForType() {
      return com.xalpol12.wsserver.protos.DrawingPayload.getDefaultInstance();
    }

    @java.lang.Override
    public com.xalpol12.wsserver.protos.DrawingPayload build() {
      com.xalpol12.wsserver.protos.DrawingPayload result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.xalpol12.wsserver.protos.DrawingPayload buildPartial() {
      com.xalpol12.wsserver.protos.DrawingPayload result = new com.xalpol12.wsserver.protos.DrawingPayload(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.xalpol12.wsserver.protos.DrawingPayload result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.drawingFrame_ = drawingFrame_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.xalpol12.wsserver.protos.DrawingPayload) {
        return mergeFrom((com.xalpol12.wsserver.protos.DrawingPayload)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.xalpol12.wsserver.protos.DrawingPayload other) {
      if (other == com.xalpol12.wsserver.protos.DrawingPayload.getDefaultInstance()) return this;
      if (!other.getDrawingFrame().isEmpty()) {
        drawingFrame_ = other.drawingFrame_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              drawingFrame_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object drawingFrame_ = "";
    /**
     * <code>string drawingFrame = 1;</code>
     * @return The drawingFrame.
     */
    public java.lang.String getDrawingFrame() {
      java.lang.Object ref = drawingFrame_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        drawingFrame_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string drawingFrame = 1;</code>
     * @return The bytes for drawingFrame.
     */
    public com.google.protobuf.ByteString
        getDrawingFrameBytes() {
      java.lang.Object ref = drawingFrame_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        drawingFrame_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string drawingFrame = 1;</code>
     * @param value The drawingFrame to set.
     * @return This builder for chaining.
     */
    public Builder setDrawingFrame(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      drawingFrame_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string drawingFrame = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearDrawingFrame() {
      drawingFrame_ = getDefaultInstance().getDrawingFrame();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string drawingFrame = 1;</code>
     * @param value The bytes for drawingFrame to set.
     * @return This builder for chaining.
     */
    public Builder setDrawingFrameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      drawingFrame_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.xalpol12.websocket.DrawingPayload)
  }

  // @@protoc_insertion_point(class_scope:com.xalpol12.websocket.DrawingPayload)
  private static final com.xalpol12.wsserver.protos.DrawingPayload DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.xalpol12.wsserver.protos.DrawingPayload();
  }

  public static com.xalpol12.wsserver.protos.DrawingPayload getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DrawingPayload>
      PARSER = new com.google.protobuf.AbstractParser<DrawingPayload>() {
    @java.lang.Override
    public DrawingPayload parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<DrawingPayload> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DrawingPayload> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.xalpol12.wsserver.protos.DrawingPayload getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

