// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

package com.xalpol12.wsserver.protos;

public interface GameTimerPayloadOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.xalpol12.websocket.GameTimerPayload)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 time = 1;</code>
   * @return The time.
   */
  int getTime();
}
