// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

package com.xalpol12.wsserver.protos;

public interface NewWordPayloadOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.xalpol12.websocket.NewWordPayload)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string newWord = 1;</code>
   * @return The newWord.
   */
  java.lang.String getNewWord();
  /**
   * <code>string newWord = 1;</code>
   * @return The bytes for newWord.
   */
  com.google.protobuf.ByteString
      getNewWordBytes();

  /**
   * <code>string newDrawer = 2;</code>
   * @return The newDrawer.
   */
  java.lang.String getNewDrawer();
  /**
   * <code>string newDrawer = 2;</code>
   * @return The bytes for newDrawer.
   */
  com.google.protobuf.ByteString
      getNewDrawerBytes();
}
