// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

package com.xalpol12.wsserver.protos;

/**
 * Protobuf type {@code com.xalpol12.websocket.NewWordPayload}
 */
public final class NewWordPayload extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.xalpol12.websocket.NewWordPayload)
    NewWordPayloadOrBuilder {
private static final long serialVersionUID = 0L;
  // Use NewWordPayload.newBuilder() to construct.
  private NewWordPayload(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private NewWordPayload() {
    newWord_ = "";
    newDrawer_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new NewWordPayload();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.xalpol12.wsserver.protos.CustomMessageProtos.internal_static_com_xalpol12_websocket_NewWordPayload_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.xalpol12.wsserver.protos.CustomMessageProtos.internal_static_com_xalpol12_websocket_NewWordPayload_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.xalpol12.wsserver.protos.NewWordPayload.class, com.xalpol12.wsserver.protos.NewWordPayload.Builder.class);
  }

  public static final int NEWWORD_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object newWord_ = "";
  /**
   * <code>string newWord = 1;</code>
   * @return The newWord.
   */
  @java.lang.Override
  public java.lang.String getNewWord() {
    java.lang.Object ref = newWord_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      newWord_ = s;
      return s;
    }
  }
  /**
   * <code>string newWord = 1;</code>
   * @return The bytes for newWord.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNewWordBytes() {
    java.lang.Object ref = newWord_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      newWord_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NEWDRAWER_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object newDrawer_ = "";
  /**
   * <code>string newDrawer = 2;</code>
   * @return The newDrawer.
   */
  @java.lang.Override
  public java.lang.String getNewDrawer() {
    java.lang.Object ref = newDrawer_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      newDrawer_ = s;
      return s;
    }
  }
  /**
   * <code>string newDrawer = 2;</code>
   * @return The bytes for newDrawer.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNewDrawerBytes() {
    java.lang.Object ref = newDrawer_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      newDrawer_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(newWord_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, newWord_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(newDrawer_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, newDrawer_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(newWord_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, newWord_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(newDrawer_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, newDrawer_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.xalpol12.wsserver.protos.NewWordPayload)) {
      return super.equals(obj);
    }
    com.xalpol12.wsserver.protos.NewWordPayload other = (com.xalpol12.wsserver.protos.NewWordPayload) obj;

    if (!getNewWord()
        .equals(other.getNewWord())) return false;
    if (!getNewDrawer()
        .equals(other.getNewDrawer())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NEWWORD_FIELD_NUMBER;
    hash = (53 * hash) + getNewWord().hashCode();
    hash = (37 * hash) + NEWDRAWER_FIELD_NUMBER;
    hash = (53 * hash) + getNewDrawer().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.xalpol12.wsserver.protos.NewWordPayload parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xalpol12.wsserver.protos.NewWordPayload parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xalpol12.wsserver.protos.NewWordPayload parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xalpol12.wsserver.protos.NewWordPayload parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xalpol12.wsserver.protos.NewWordPayload parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xalpol12.wsserver.protos.NewWordPayload parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xalpol12.wsserver.protos.NewWordPayload parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xalpol12.wsserver.protos.NewWordPayload parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.xalpol12.wsserver.protos.NewWordPayload parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.xalpol12.wsserver.protos.NewWordPayload parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.xalpol12.wsserver.protos.NewWordPayload parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xalpol12.wsserver.protos.NewWordPayload parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.xalpol12.wsserver.protos.NewWordPayload prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.xalpol12.websocket.NewWordPayload}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.xalpol12.websocket.NewWordPayload)
      com.xalpol12.wsserver.protos.NewWordPayloadOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xalpol12.wsserver.protos.CustomMessageProtos.internal_static_com_xalpol12_websocket_NewWordPayload_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xalpol12.wsserver.protos.CustomMessageProtos.internal_static_com_xalpol12_websocket_NewWordPayload_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xalpol12.wsserver.protos.NewWordPayload.class, com.xalpol12.wsserver.protos.NewWordPayload.Builder.class);
    }

    // Construct using com.xalpol12.wsserver.protos.NewWordPayload.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      newWord_ = "";
      newDrawer_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.xalpol12.wsserver.protos.CustomMessageProtos.internal_static_com_xalpol12_websocket_NewWordPayload_descriptor;
    }

    @java.lang.Override
    public com.xalpol12.wsserver.protos.NewWordPayload getDefaultInstanceForType() {
      return com.xalpol12.wsserver.protos.NewWordPayload.getDefaultInstance();
    }

    @java.lang.Override
    public com.xalpol12.wsserver.protos.NewWordPayload build() {
      com.xalpol12.wsserver.protos.NewWordPayload result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.xalpol12.wsserver.protos.NewWordPayload buildPartial() {
      com.xalpol12.wsserver.protos.NewWordPayload result = new com.xalpol12.wsserver.protos.NewWordPayload(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.xalpol12.wsserver.protos.NewWordPayload result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.newWord_ = newWord_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.newDrawer_ = newDrawer_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.xalpol12.wsserver.protos.NewWordPayload) {
        return mergeFrom((com.xalpol12.wsserver.protos.NewWordPayload)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.xalpol12.wsserver.protos.NewWordPayload other) {
      if (other == com.xalpol12.wsserver.protos.NewWordPayload.getDefaultInstance()) return this;
      if (!other.getNewWord().isEmpty()) {
        newWord_ = other.newWord_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getNewDrawer().isEmpty()) {
        newDrawer_ = other.newDrawer_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              newWord_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              newDrawer_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object newWord_ = "";
    /**
     * <code>string newWord = 1;</code>
     * @return The newWord.
     */
    public java.lang.String getNewWord() {
      java.lang.Object ref = newWord_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        newWord_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string newWord = 1;</code>
     * @return The bytes for newWord.
     */
    public com.google.protobuf.ByteString
        getNewWordBytes() {
      java.lang.Object ref = newWord_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        newWord_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string newWord = 1;</code>
     * @param value The newWord to set.
     * @return This builder for chaining.
     */
    public Builder setNewWord(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      newWord_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string newWord = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearNewWord() {
      newWord_ = getDefaultInstance().getNewWord();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string newWord = 1;</code>
     * @param value The bytes for newWord to set.
     * @return This builder for chaining.
     */
    public Builder setNewWordBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      newWord_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object newDrawer_ = "";
    /**
     * <code>string newDrawer = 2;</code>
     * @return The newDrawer.
     */
    public java.lang.String getNewDrawer() {
      java.lang.Object ref = newDrawer_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        newDrawer_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string newDrawer = 2;</code>
     * @return The bytes for newDrawer.
     */
    public com.google.protobuf.ByteString
        getNewDrawerBytes() {
      java.lang.Object ref = newDrawer_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        newDrawer_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string newDrawer = 2;</code>
     * @param value The newDrawer to set.
     * @return This builder for chaining.
     */
    public Builder setNewDrawer(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      newDrawer_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string newDrawer = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearNewDrawer() {
      newDrawer_ = getDefaultInstance().getNewDrawer();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string newDrawer = 2;</code>
     * @param value The bytes for newDrawer to set.
     * @return This builder for chaining.
     */
    public Builder setNewDrawerBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      newDrawer_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.xalpol12.websocket.NewWordPayload)
  }

  // @@protoc_insertion_point(class_scope:com.xalpol12.websocket.NewWordPayload)
  private static final com.xalpol12.wsserver.protos.NewWordPayload DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.xalpol12.wsserver.protos.NewWordPayload();
  }

  public static com.xalpol12.wsserver.protos.NewWordPayload getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<NewWordPayload>
      PARSER = new com.google.protobuf.AbstractParser<NewWordPayload>() {
    @java.lang.Override
    public NewWordPayload parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<NewWordPayload> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<NewWordPayload> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.xalpol12.wsserver.protos.NewWordPayload getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

